[package]
name = "screen_capturer"
version = "0.1.0"
authors = ["TKGgunter <thothgunter@live.com>"]

[dependencies]
glium = "*"
nalgebra = "*"

[target.'cfg(windows)'.dependencies]
winapi = {version="0.3.7", features = ["libloaderapi"]}
